services:
  apache:
    profiles: ["run"]
    container_name: mage-apache
    build: ./apache
    volumes:
      - ./apache/logs:/usr/local/apache2/logs/httpd:rw
      - ./webroot:/usr/local/apache2/htdocs:ro
    networks:
      - mage
    restart: unless-stopped

  nginx:
    profiles: ["run"]
    container_name: mage-nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/logs:/var/log/nginx:rw
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./letsencrypt/cert:/etc/letsencrypt:ro
      - ./letsencrypt/web:/var/www/certbot:ro
    environment:
      - CERT_DOMAIN=
    networks:
      - mage
    restart: unless-stopped

  certbot-watch:
    profiles: ["run"]
    container_name: certbot-watch
    image: certbot/certbot
    environment:
      - TZ=Europe/Kiev
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./letsencrypt/cert:/etc/letsencrypt:rw
      - ./letsencrypt/web:/var/www/certbot:rw
    networks:
      - mage
    depends_on:
      - nginx

  # this service only generates certificates and exits
  certbot-generate-cert:
    profiles: ["gen"]
    image: certbot/certbot
    container_name: certbot-generate
    environment:
      - TZ=Europe/Kiev
      - DOMAIN=
      - EMAIL=
    ports:
      - 80:80
    volumes:
      - ./letsencrypt/cert:/etc/letsencrypt:rw
      - ./letsencrypt/web:/var/www/certbot:rw
    entrypoint: "/bin/sh -c 'certbot certonly --standalone -d $${DOMAIN} --non-interactive --agree-tos --no-eff-email --email $${EMAIL}'"

networks:
  mage:
    name: mage-net
    driver: bridge
