services:
  apache:
    build: ./apache
    volumes:
      - ./webroot:/usr/local/apache2/htdocs
      - ./apache/logs:/usr/local/apache2/logs/httpd
    networks:
      - clan
  
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - clan

networks:
  clan:
    driver: bridge

