services:
  apache:
    container_name: mage-apache
    build: ./apache
    volumes:
      - ./apache/logs:/usr/local/apache2/logs/httpd:rw
      - ./webroot:/usr/local/apache2/htdocs:ro
    networks:
      - mage
    restart: unless-stopped

  nginx:
    container_name: mage-nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/logs:/var/log/nginx:rw
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./letsencrypt/conf:/etc/letsencrypt:ro
      - ./letsencrypt/acme:/var/www/certbot:ro
    environment:
      - DOMAIN
    networks:
      - mage
    restart: unless-stopped

  certbot:
    container_name: mage-certbot
    image: certbot/certbot
    command: >
      certonly --reinstall --webroot 
      --webroot-path /var/www/certbot/
      --noninteractive --agree-tos
      --email ${EMAIL} --no-eff-email
      --cert-name mage -d ${DOMAIN}
    volumes:
      - ./letsencrypt/conf:/etc/letsencrypt:rw
      - ./letsencrypt/acme:/var/www/certbot:rw
    networks:
      - mage
    depends_on:
      - nginx

networks:
  mage:
    name: mage-net
    driver: bridge

