networks:
  scific:
    name: mage-scific
    driver: bridge

services:
  apache:
    container_name: mage-apache
    build: ./apache
    image: mage/apache
    volumes:
      - ./apache/logs:/usr/local/apache2/logs/httpd:rw
      - ./scific:/usr/local/apache2/htdocs:ro
    networks:
      - scific

  nginx:
    container_name: mage-nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/logs:/var/log/nginx:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/crontab:/etc/crontab:ro
      - ./letsencrypt/conf/live:/etc/nginx/cert.d:ro
      - ./letsencrypt/acme:/var/www/certbot:ro
    networks:
      - scific
    # restart: unless-stopped

  # certbot:
  #   container_name: mage-certbot
  #   image: certbot/certbot
  #   entrypoint: >
  #     certbot certonly 
  #     --webroot --webroot-path /var/www/certbot/
  #     --noninteractive --agree-tos
  #     --email {{ email }} --no-eff-email
  #     --cert-name scific -d {{ domain }} && 
  #   command: "tail -f /var/log/letsencrypt"
  #   volumes:
  #     - ./letsencrypt/conf:/etc/letsencrypt:rw
  #     - ./letsencrypt/acme:/var/www/certbot:rw
  #     - ./letsencrypt/crontab:/etc/crontab:ro
  #   depends_on: nginx
