networks:
  scific:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/29

services:
  apache:
    build: ./apache
    volumes:
      - ./scific:/usr/local/apache2/htdocs
      - ./apache/logs:/usr/local/apache2/logs/httpd
    networks:
      scific:
        ipv4_address: 192.168.0.2
  
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      scific:
        ipv4_address: 192.168.0.3
